f# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NlKItYeOAjKm0wyWXoLOYDSeA_782MsK
"""

# --- PROGRAMA BASE: ASISTENTE DE RESTAURANTE ---

def mostrar_menu():
    print("\n--- 🍽️ MENÚ DEL RESTAURANTE COLAB ---")
    print("1. Ver el menú del día")
    print("2. Tomar un pedido")
    print("3. Personalizar nombre del cliente")
    print("4. Salir")
    print("5. Calcular precio total con IVA")

def ejecutar_asistente():
    cliente = "Cliente" # Variable para el nombre del cliente
    continuar = True
    while continuar:
        mostrar_menu()
        opcion = input("Seleccione una opción (1-5): ")

        if opcion == "1":
            print("\n--- MENÚ DEL DÍA ---")
            print("- Plato principal: Paella Mixta")
            print("- Postre: Tarta de Queso")
            print("- Bebida: Agua o Refresco")
        elif opcion == "2":
            print(f"\n¡Tomando el pedido para {cliente}!")
            input("Presiona Enter para confirmar el pedido...") # Simula tomar un pedido
            print("Pedido registrado con éxito.")
        elif opcion == "3":
            nuevo_cliente = input("Introduce el nuevo nombre del cliente: ")
            if nuevo_cliente:
                cliente = nuevo_cliente
                print(f"Nombre del cliente actualizado a '{cliente}'.")
            else:
                print("El nombre del cliente no puede estar vacío.")
        elif opcion == "4":
            print("\n¡Gracias por tu visita al Restaurante Colab! ¡Vuelve pronto!")
            continuar = False
        elif opcion == "5":
            try:
                precio_base = float(input("Introduce el precio base de los productos: "))
                iva = float(input("Introduce el porcentaje de IVA (ej. 21 para 21%): "))
                precio_total = precio_base * (1 + iva / 100)
                print(f"El precio total con IVA es: {precio_total:.2f}€")
            except ValueError:
                print("Por favor, introduce valores numéricos válidos.")
        else:
            print("Opción no válida. Por favor, intente de nuevo.")

# Iniciar el programa
ejecutar_asistente()